mac80211: add led_trigger_blink{_oneshot}()
When led support is deactivated in the kernel and
CPTCFG_BACKPORT_BUILD_LEDS is set mac80211 references
led_trigger_blink_oneshot() but it is not declared anywhere.

This fixes the following build error:
net/mac80211/led.c: In function 'ieee80211_led_rx':
net/mac80211/led.c:25:2: error: implicit declaration of function 'led_trigger_blink_oneshot' [-Werror=implicit-function-declaration]

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

SVN-Revision: 39530